---
- name: Cronjob for checking and setting Password Aging for human accounts
  cron:
    name: "set_password_aging"
    minute: "20"
    hour: "02"
    job: "/usr/gdyr/adm/set_password_aging 1>/dev/null 2>&1"
  tags: cron
- name: Create password-policy file
  shell: authselect create-profile goodyear-policy --base-on=sssd --symlink-meta
  ignore_errors: yes
- lineinfile: path=/etc/authselect/custom/goodyear-policy/password-auth insertafter='^password    requisite                                    pam_pwquality.so local_users_only' line='password    requisite                                    pam_pwhistory.so use_authtok enforce_for_root remember=5 retry=3'
- lineinfile: path=/etc/authselect/custom/goodyear-policy/system-auth  insertafter='^password    requisite                                    pam_pwquality.so local_users_only' line='password    requisite                                    pam_pwhistory.so use_authtok enforce_for_root remember=5 retry=3'
- name: Enable custom GY password policy
  shell: "authselect select custom/goodyear-policy with-faillock --backup=sssd.original --force"
- name: Insert password standards in pwquality.conf file
  shell:
#    cmd: sed -i  's/^/#/' /etc/security/pwquality.conf
    cmd: sed -i 's/^\([^#]\)/#\1/' /etc/security/pwquality.conf
- lineinfile:
    path: /etc/security/pwquality.conf
    line: "{{ item }}"
    state: present
  loop:
     - 'minlen = 15'
     - 'dcredit = -1'
     - 'lcredit = -1'
     - 'ucredit = 0'
     - 'ocredit = 0'
     - 'maxrepeat = 3'
     - 'dictcheck = 1'
     - 'usercheck = 1'
     - 'enforce_for_root'

#- blockinfile:
#   path: /etc/security/pwquality.conf
#   block: |
#    minlen = 15
#    dcredit = -1
#    lcredit = -1
#    ucredit = 0
#    ocredit = 0
#    maxrepeat = 3
#    dictcheck = 1
#    usercheck = 1
#    enforce_for_root
- name: Enable faillock
  shell:
#    cmd: sed -i 's/^/#/' /etc/security/faillock.conf
    cmd: sed -i 's/^\([^#]\)/#\1/' /etc/security/faillock.conf
- lineinfile:
    path: /etc/security/faillock.conf
    line: "{{ item }}"
    state: present
  loop:
     - 'silent'
     - 'audit'
     - 'deny = 6'
     - 'even_deny_root'
     - 'root_unlock_time = 900'
     - 'unlock_time = 0'
     - 'dir = /var/log/faillock'

#- blockinfile:
#   path: /etc/security/faillock.conf
#   block: |
#    silent
#    audit
#    deny = 6
#    even_deny_root
#    root_unlock_time = 900
#    unlock_time = 0
#    dir = /var/log/faillock
- name: Create faillog logs directory
  file: path=/var/log/faillock state=directory mode=0755
