- name: Security hardening (2024/06/26)
  debug:
    msg: "RHEL-9 security hardening"
- name: Enable BIOS Password
  debug:
    msg: "UEFI is used which do not allow administrative password to be set"
- name: Kernel Paramaters
  debug:
    msg: |
           Disable IPv4 ICMP redirect
           Prevent network flooding
           Force disabling of IPv4 forwarding
           Randomize VA space
           Prevent SUID binaries to generate dumps
- copy:
    src: files/50-GY_hardening.conf
    dest: /etc/sysctl.d/50-GY_hardening.conf
    mode: 0644
    owner: root
    group: root
- name: Disable nonsecure kernel modules
  debug:
    msg: |
        - TIPC
        - squashfs
        - udf
        - USB-storage
- copy: src=files/GY_hardening.conf dest=/etc/modprobe.d/GY_hardening.conf owner=root group=root mode=0644
- name: Partition mount options
  debug:
    msg: >-
     To check for partition mounting weakness, we consider the following criteria:
       All partitions other than '/', '/dev', '/sys', and '/proc' should have the following options set:        nodev
       /home should have the following options set:                                                             nosuid
       /tmp and /var should have the following options set:                                                     nosuid,noexec
       /etc should have the following options set:                                                              nosuid,noexec
- mount:
   backup: true
   path: /opt/CrowdStrike
   src: /dev/mapper/vg00-lvcrowdstrike 
   fstype: xfs
   opts: defaults,nodev
   state: mounted 
  tags: tt
- mount:
   path: /opt/managesoft
   src: /dev/mapper/vg00-lvmanagesoft
   fstype: xfs
   opts: defaults,nodev
   state: mounted
  tags: tt

- mount:
   path: /opt/rapid7
   src: /dev/mapper/vg00-lvrapid7
   fstype: xfs
   opts: defaults,nodev
   state: mounted
  ignore_errors: true
  tags: tt

- mount:
   path: /boot
   opts: defaults,nodev
   state: mounted
  tags: tt
  ignore_errors: true

- mount:
   path: /home
   src: /dev/mapper/vg00-lvhome
   fstype: xfs
   opts: defaults,nodev,nosuid
   state: mounted
  tags: tt

- mount:
   path: /tmp
   src: /dev/mapper/vg00-lvtmp
   fstype: xfs
   opts: defaults,nodev,nosuid,noexec
   state: mounted
  tags: tt

- mount:
   path: /var
   src: /dev/mapper/vg00-lvvar
   fstype: xfs
   opts: defaults,nodev,nosuid,noexec
   state: mounted
  tags: tt

- mount:
   path: /etc
   opts: defaults,nodev,nosuid,noexec
   state: mounted
  ignore_errors: true
  tags: tt

- mount:
   path: /opt
   src: /dev/mapper/vg00-lvopt
   fstype: xfs
   opts: defaults,nodev
   state: mounted
  tags: tt


- name: SSHD Hardnening
  copy: src=files/99-GY-hardening.conf dest=/etc/ssh/sshd_config.d/99-GY-hardening.conf mode=0644 owner=root group=root

- name: World writable directories
  file:
    path: /usr/gdyr/lib 
    mode: 0755
    state: directory
- file: 
    path: /usr/gdyr/var 
    mode: 0755
    state: directory

- name: Enforce root login only through allowed consoles
  lineinfile:
    path: /etc/pam.d/login
    backup: yes
    insertafter: '#%PAM-1.0'
    firstmatch: yes
    line: "auth [user_unknown=ignore success=ok ignore=ignore default=bad] pam_securetty.so"
    state: present

- lineinfile: 
    path: /etc/pam.d/remote
    backup: yes
    insertafter: '#%PAM-1.0'
    firstmatch: yes
    line: "auth       required     pam_securetty.so"
    state: present
- command: cat /sys/class/dmi/id/sys_vendor
  register: archi
- lineinfile:
    path: /etc/securetty
    line: 'console'
    state: present
  loop:
     - 'console'
     - 'vc/1'
     - 'vc/2'
     - 'vc/3'
     - 'vc/4'
     - 'vc/5'
     - 'vc/6'
     - 'vc/7'
     - 'vc/8'
     - 'vc/9'
     - 'vc/10'
     - 'vc/11'
     - 'tty1'
     - 'tty2'
     - 'tty3'
     - 'tty4'
     - 'tty5'
     - 'tty6'
     - 'tty7'
     - 'tty8'
     - 'tty9'
     - 'tty10'
     - 'tty11'
#  when: 'archi.stdout != "VMware, Inc."'
  ignore_errors: true
- lineinfile:
    path: /etc/securetty
    state: absent
    search_string: "ANSIBLE"
  ignore_errors: true
- command: cat /etc/securetty
  register: sty
- debug:
    msg: "{{ sty.stdout_lines }}"
- name: Password policy enforcement
  shell:
    cmd: authselect select custom/goodyear-policy with-faillock without-nullok --backup=sssd.original --force
- command: authselect current
  register: ac
- debug:
    msg: "{{ ac.stdout_lines }}"
- name: journald
  debug:
    msg: |
            - Enable compress on journald big files
            - Enable journald to send to syslog
            - Enable journald to store data to persistent storage
- lineinfile:
    path: /etc/systemd/journald.conf
    firstmatch: yes
    search_string: '^Storage='
    insertbefore: '^#Seal=yes'
    line: 'Storage=persistent'
    state: present
- lineinfile:
    path: /etc/systemd/journald.conf
    firstmatch: yes
    search_string: 'Compress='
    insertbefore: '^#Seal=yes'
    line: 'Compress=yes'
    state: present
- lineinfile:
    path: /etc/systemd/journald.conf
    firstmatch: yes
    search_string: 'ForwardToSyslog'
    line: 'ForwardToSyslog=yes'
    insertbefore: '^#ForwardToKMsg=no'
    state: present
- lineinfile:
    path: /etc/systemd/journald.conf
    search_string: 'Audit='
    line: 'Audit='
    state: present

- name: Display ourput of Journald.conf file
  shell:
    cmd: grep -Ev "^#" /etc/systemd/journald.conf
  register: jd
- debug:
    msg: "{{ jd.stdout_lines }}"

- name: rsyslog files permission
  copy: src=files/GY_custom.conf dest=/etc/rsyslog.d/GY_custom.conf mode=0644 owner=root group=root
- file:
   path: "{{ item }}"
   mode: 0644
   owner: root
   group: root
  with_items:
   - '/var/log/secure'
   - '/var/log/messages'
   - '/var/log/cron'
   - '/var/log/maillog'
   - '/var/log/boot.log'
   - '/var/log/spooler'
  ignore_errors: yes

- name: Disable inactive accounts 30 days after password expiry
  lineinfile:
    path: /etc/default/useradd
    regexp: '^INACTIVE='
    line: 'INACTIVE=30'
    state: present
  ignore_errors: yes
- command: cat /etc/default/useradd
  register: INac
- debug:
    msg: "{{ INac.stdout_lines }}"

- name: Time-out sessions after 1 hour
  copy: src=files/tmout.sh dest=/etc/profile.d/tmout.sh mode=0644 owner=root group=root

- name: Cron Permissions
  file: 
   path: "{{ item }}"
   mode: 0700
  with_items:
    - '/etc/cron.d'
    - '/etc/cron.daily'
    - '/etc/cron.hourly'
    - '/etc/cron.monthly'
    - '/etc/cron.weekly'
    - '/etc/crontab'
  ignore_errors: true

- name: Force postfix to listen only on loopback interface
  shell:
    cmd: postconf -e inet_interfaces=loopback-only
- name: Strengthen default user umask
  lineinfile:
    path: /etc/bashrc
    line: '# GY hardening'
    state: present
  loop:
    - '# GY hardening'
    - 'umask 027'
- lineinfile:
    path: /etc/profile
    line: '# GY hardening'
    state: present
  loop:
    - '# GY hardening'
    - 'umask 027'

- shell:
    cmd: 'grep -E ^UMASK /etc/login.defs'
  register: um
- command: tail -5 /etc/bashrc
  register: rc
- command: tail -5 /etc/profile
  register: le

- debug:
    msg: "{{ um }}"
- debug:
    msg: "{{ rc }}"
- debug:
    msg: "{{ le }}"

#- debug:
#    msg: "{{ bashrc file last 5-lines are {{ rc.stdout_lines }}, UMASK in login-defs is {{ um.stdout_lines }} and last 5-lines of profile file are {{ le.stdout_lines }} }}"

- name: Restrict SSH key logins (2024/07/03)
  group:
    name: AllowSSHPubKey
    gid: 8169
    state: present
- user:
    name: "{{ item }}"
    groups: AllowSSHPubKey
    append: true
  with_items:
    - root
    - ld66011

- copy:
   src: files/99-GY-hardening.conf
   dest: /etc/ssh/sshd_config.d/99-GY-hardening.conf
